------- CRIACAO DAS TABELAS
CREATE EXTENSION IF NOT EXISTS unaccent;

-- 1. InstituicaoSaude (Supertype)
CREATE TABLE InstituicaoSaude (
    CNPJ CHAR(18),
    nome VARCHAR(40) NOT NULL,
    cidade VARCHAR(40),
    estado VARCHAR(2),
    logradouro VARCHAR(100),
    CONSTRAINT PK_INSTITUICAO PRIMARY KEY(Id),
    CONSTRAINT CHK_INSTITUICAO CHECK (CNPJ ~ '^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$')
);

-- 2. Subtypes of InstituicaoSaude
CREATE TABLE Hospital (
    CNPJ CHAR(18),
    CONSTRAINT PK_HOSPITAL PRIMARY KEY(CNPJ),
    CONSTRAINT FK_HOSPITAL FOREIGN KEY (CNPJ) REFERENCES InstituicaoSaude(CNPJ) ON DELETE CASCADE
);

CREATE TABLE Hemocentro (
    CNPJ CHAR(18),
    CONSTRAINT PK_HEMOCENTRO PRIMARY KEY(CNPJ),
    CONSTRAINT FK_HEMOCENTRO FOREIGN KEY (CNPJ) REFERENCES InstituicaoSaude(CNPJ) ON DELETE CASCADE
);

CREATE TABLE CentroDeColeta (
    CNPJ CHAR(18),
    codigo VARCHAR(10),
    cidade VARCHAR(40),
    estado VARCHAR(2),
    logradouro VARCHAR(100),
    ativo BOOLEAN NOT NULL,
    dataAbertura DATE,
    dataFechamento DATE,
    CONSTRAINT PK_COLETA PRIMARY KEY (CNPJ, codigo),
    CONSTRAINT FK_COLETA FOREIGN KEY (CNPJ) REFERENCES InstituicaoSaude(CNPJ) ON DELETE CASCADE,
    CONSTRAINT CK_ABERTUTA CHECK (dataAbertura <= dataFechamento)
);

-- 3. TipoInstituicao (Multivalued Attribute / Classification)
CREATE TABLE TipoInstituicao (
    CNPJ CHAR(18),
    tipo VARCHAR(20),
    CONSTRAINT PK_TIPOINST PRIMARY KEY (CNPJ, tipo),
    CONSTRAINT FK_TIPOINST FOREIGN KEY (CNPJ) REFERENCES InstituicaoSaude(CNPJ) ON DELETE CASCADE,
    CONSTRAINT CHK_TIPOINST CHECK (tipo IN ('CENTRO COLETA', 'BANCO DE SANGUE', 'HOSPITAL', 'HEMOCENTRO'))
);

-- 4. EstoqueSangue
CREATE TABLE EstoqueSangue (
    InstituicaoSaude CHAR(18),
    NumOMinus INTEGER,
    NumAMinus INTEGER,
    NumBMinus INTEGER,
    NumABMinus INTEGER,
    NumOPlus INTEGER,
    NumAPlus INTEGER,
    NumBPlus INTEGER,
    NumABPlus INTEGER,
    CONSTRAINT PK_ESTOQUESANGUE PRIMARY KEY(InstituicaoSaude),
    CONSTRAINT FK_ESTOQUESANGUE FOREIGN KEY (InstituicaoSaude) REFERENCES InstituicaoSaude(CNPJ) ON DELETE CASCADE
    CONSTRAINT CHK_OM CHECK (NumOMinus >=0),
    CONSTRAINT CHK_AM CHECK (NumAMinus >=0),
    CONSTRAINT CHK_BM CHECK (NumBMinus >=0),
    CONSTRAINT CHK_ABM CHECK (NumABMinus >=0),
    CONSTRAINT CHK_OP CHECK (NumOPlus >=0),
    CONSTRAINT CHK_AP CHECK (NumAPlus >=0),
    CONSTRAINT CHK_BP CHECK (NumBPlus >=0),
    CONSTRAINT CHK_ABP CHECK (NumABPlus >=0)
);

-- 5. Pessoa (Supertype)
CREATE TABLE Pessoa (
    Id VARCHAR(10),
    CPF CHAR(14),
    nome VARCHAR(40) NOT NULL,
    genero VARCHAR(20),
    tiposanguineo CHAR(3),
    cidade VARCHAR(40),
    estado CHAR(2),
    logradouro VARCHAR(100),
    dataNascimento DATE NOT NULL,
    telefone CHAR(13),
    email VARCHAR(30),
    CONSTRAINT PK_PESSOA PRIMARY KEY(Id),
    CONSTRAINT UK_PESSOA UNIQUE(CPF),
    CONSTRAINT CHK_GENERO CHECK (genero IN ('MASCULINO', 'FEMININO', 'OUTRO')),
    CONSTRAINT CHK_CPF CHECK (cpf ~ '^\d{3}\.\d{3}\.\d{3}-\d{2}$'),
    CONSTRAINT CHK_TELEFONE CHECK (telefone ~ '^\d{2} \d{5}-\d{4}$'),
    CONSTRAINT CHK_EMAIL CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT CHK_TIPOSANGUINEO CHECK (tiposanguineo IN ('O-', 'A-', 'B-', 'AB-', 'O+', 'A+', 'B+', 'AB+'))
);

-- 6. TipoPessoa (Multivalued Attribute)
CREATE TABLE TipoPessoa (
    Id VARCHAR(10),
    tipo VARCHAR(20),
    CONSTRAINT PK_TIPOPESSOA PRIMARY KEY (Id, tipo),
    CONSTRAINT FK_TIPOPESSOA FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

-- 7. Subtypes of Pessoa (Profesionais)
CREATE TABLE Biomedico (
    Id VARCHAR(10),
    CRBM VARCHAR(10),
    CONSTRAINT PK_BIOMEDICO PRIMARY KEY(Id),
    CONSTRAINT UK_BIOMEDICO UNIQUE(CRBM),
    CONSTRAINT FK_BIOMEDICO FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE TABLE Enfermeiro (
    Id VARCHAR(10),
    COREN VARCHAR(10),
    CONSTRAINT PK_ENFERMEIRO PRIMARY KEY(Id),
    CONSTRAINT UK_ENFERMEIRO UNIQUE(COREN),
    CONSTRAINT FK_ENFERMEIRO FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE TABLE Medico (
    Id VARCHAR(10),
    CRM VARCHAR(10),
    CONSTRAINT PK_ENFERMEIRO PRIMARY KEY(Id),
    CONSTRAINT UK_ENFERMEIRO UNIQUE(CRM),
    CONSTRAINT FK_MEDICO FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE TABLE AgenteMapeamento (
    Id VARCHAR(10),
    CONSTRAINT PK_AGENTE PRIMARY KEY(Id),
    CONSTRAINT FK_AGENTE FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

-- 8. Subtypes of Pessoa (Clients)
CREATE TABLE Doador (
    Id VARCHAR(10),
    peso DECIMAL(5,2),
    altura DECIMAL(3,2),
    CONSTRAINT PK_DOADOR PRIMARY KEY(Id),
    CONSTRAINT FK_DOADOR FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE,
    CONSTRAINT CK_PESO_DOAD CHECK (peso > 0.0),
    CONSTRAINT CK_ALT_DOAD CHECK (altura > 0.0)
);

CREATE TABLE Receptor (
    Id VARCHAR(10),
    CONSTRAINT PK_RECEPTOR PRIMARY KEY,
    CONSTRAINT FK_RECEPTOR FOREIGN KEY (Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

-- 9. Multivalued Attributes for Clients
CREATE TABLE ISTDoador (
    Id VARCHAR(10),
    IST VARCHAR(50),
    CONSTRAINT PK_ISTDOADOR PRIMARY KEY (Id, IST),
    CONSTRAINT FK_ISTDOADOR FOREIGN KEY (Id) REFERENCES Doador(Id) ON DELETE CASCADE
);

CREATE TABLE MotivoReceptor (
    Id VARCHAR(10),
    motivo VARCHAR(100),
    CONSTRAINT PK_MOTIVOREC PRIMARY KEY (Id, motivo),
    CONSTRAINT FK_MOTIVOREC FOREIGN KEY (Id) REFERENCES Receptor(Id) ON DELETE CASCADE
);

-- 10. Triagem
CREATE TABLE Triagem (
    IdTriagem VARCHAR(10),
    Doador VARCHAR(10) NOT NULL,
    DataHora TIMESTAMP NOT NULL,
    Enfermeiro VARCHAR(10) NOT NULL,
    Valido BOOLEAN,
    CentroColeta_CNPJ CHAR(18) NOT NULL,
    CentroColeta_Codigo VARCHAR(10) NOT NULL,
    CONSTRAINT PK_TRIAGEM PRIMARY KEY (IdTriagem),
    CONSTRAINT FK1_TRIAGEM FOREIGN KEY (Doador) REFERENCES Doador(Id) ON DELETE CASCADE,
    CONSTRAINT FK2_TRIAGEM FOREIGN KEY (Enfermeiro) REFERENCES Enfermeiro(Id) ON DELETE CASCADE,
    CONSTRAINT FK3_TRIAGEM FOREIGN KEY (CentroColeta_CNPJ, CentroColeta_Codigo) REFERENCES CentroDeColeta(CNPJ, codigo) ON DELETE CASCADE
);

-- 11. BolsaSangue
CREATE TABLE BolsaSangue (
    Codigo VARCHAR(20),
    VolumeDoado INTEGER NOT NULL,
    TipoSangue CHAR(3),
    Valido BOOLEAN,
    Triagem VARCHAR(10) NOT NULL,
    Biomedico VARCHAR(10),
    Hemocentro VARCHAR(40),
    DataTestagem DATE,
    CONSTRAINT PK_BOLSA PRIMARY KEY(Codigo),
    CONSTRAINT FK1_BOLSA FOREIGN KEY (Triagem) REFERENCES Triagem(IdTriagem) ON DELETE CASCADE,
    CONSTRAINT FK2_BOLSA FOREIGN KEY (Biomedico) REFERENCES Biomedico(Id) ON DELETE CASCADE,
    CONSTRAINT FK3_BOLSA FOREIGN KEY (Hemocentro) REFERENCES Hemocentro(CNPJ) ON DELETE CASCADE
);

-- 12. Procedimento
CREATE TABLE Procedimento (
    Receptor VARCHAR(10),
    DataHora TIMESTAMP,
    Medico VARCHAR(10),
    Hospital VARCHAR(40),
    CONSTRAINT PK_PROCEDIMENTO PRIMARY KEY (Receptor, DataHora, Medico, Hospital),
    CONSTRAINT FK1_PROCEDIMENTO FOREIGN KEY (Receptor) REFERENCES Receptor(Id) ON DELETE CASCADE,
    CONSTRAINT FK2_PROCEDIMENTO FOREIGN KEY (Medico) REFERENCES Medico(Id) ON DELETE CASCADE,
    CONSTRAINT FK3_PROCEDIMENTO FOREIGN KEY (Hospital) REFERENCES Hospital(CNPJ) ON DELETE CASCADE
);

-- 13. Pesquisa
CREATE TABLE Pesquisa (
    Doador VARCHAR(10),
    DataHora TIMESTAMP,
    AgenteMapeamento VARCHAR(10),
    Doou BOOLEAN,
    PrimeiraDoacao BOOLEAN,
    DoariaNovamente BOOLEAN,
    Feedback VARCHAR(255),
    CONSTRAINT PK_PESQUISA PRIMARY KEY (Doador, DataHora, AgenteMapeamento),
    CONSTRAINT FK1_PESQUISA FOREIGN KEY (Doador) REFERENCES Doador(Id) ON DELETE CASCADE,
    CONSTRAINT FK2_PESQUISA FOREIGN KEY (AgenteMapeamento) REFERENCES AgenteMapeamento(Id) ON DELETE CASCADE
);

-- 14. Solicitacao
CREATE TABLE Solicitacao (
    Hospital VARCHAR(40),
    DataHora TIMESTAMP,
    Hemocentro VARCHAR(40),
    QntOPlus INTEGER,
    QntOMinus INTEGER,
    QntAPlus INTEGER,
    QntAMinus INTEGER,
    QntBPlus INTEGER,
    QntBMinus INTEGER,
    QntABPlus INTEGER,
    QntABMinus INTEGER,
    AceitaNegada BOOLEAN,
    CONSTRAINT PK_SOLICITACAO PRIMARY KEY (Hospital, DataHora, Hemocentro) ON DELETE CASCADE,
    CONSTRAINT FK1_SOLICITACAO FOREIGN KEY (Hospital) REFERENCES Hospital(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FK2_SOLICITACAO FOREIGN KEY (Hemocentro) REFERENCES Hemocentro(CNPJ) ON DELETE CASCADE,
    CONSTRAINT CHK_OM CHECK (QntOMinuss >=0),
    CONSTRAINT CHK_AM CHECK (QntAMinus >=0),
    CONSTRAINT CHK_BM CHECK (QntBMinus >=0),
    CONSTRAINT CHK_ABM CHECK (QntABMinus >=0),
    CONSTRAINT CHK_OP CHECK (QntOPlus >=0),
    CONSTRAINT CHK_AP CHECK (QntAPlus >=0),
    CONSTRAINT CHK_BP CHECK (QntBPlus >=0),
    CONSTRAINT CHK_ABP CHECK (QntABPlus >=0)
);

-- 15. Transferencia
CREATE TABLE Transferencia (
    HemoOrigem VARCHAR(40),
    HemoDestino VARCHAR(40),
    DataHora TIMESTAMP,
    QntOPlus INTEGER,
    QntOMinus INTEGER,
    QntAPlus INTEGER,
    QntAMinus INTEGER,
    QntBPlus INTEGER,
    QntBMinus INTEGER,
    QntABPlus INTEGER,
    QntABMinus INTEGER,
    AceitaNegada BOOLEAN,
    CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (HemoOrigem, HemoDestino, DataHora),
    CONSTRAINT FK1_TRANSFERENCIA FOREIGN KEY (HemoOrigem) REFERENCES Hemocentro(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FK2_TRANSFERENCIA FOREIGN KEY (HemoDestino) REFERENCES Hemocentro(CNPJ) ON DELETE CASCADE,
    CONSTRAINT CHK_OM CHECK (QntOMinuss >=0),
    CONSTRAINT CHK_AM CHECK (QntAMinus >=0),
    CONSTRAINT CHK_BM CHECK (QntBMinus >=0),
    CONSTRAINT CHK_ABM CHECK (QntABMinus >=0),
    CONSTRAINT CHK_OP CHECK (QntOPlus >=0),
    CONSTRAINT CHK_AP CHECK (QntAPlus >=0),
    CONSTRAINT CHK_BP CHECK (QntBPlus >=0),
    CONSTRAINT CHK_ABP CHECK (QntABPlus >=0)
);

-- 16. Usuario (Authentication)
CREATE TABLE Usuario (
    Login VARCHAR(50),
    Senha VARCHAR(50) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    PessoaId VARCHAR(10),
    CONSTRAINT PK_USUARIO PRIMARY KEY(Login),
    CONSTRAINT FK_USUARIO_PESSOA FOREIGN KEY (PessoaId) REFERENCES Pessoa(Id)
);

-- 17. RBAC (Permissions)
CREATE TABLE Permissao (
    Id INT PRIMARY KEY,
    Nome VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RolePermissao (
    Role VARCHAR(20),
    PermissaoId INT,
    PRIMARY KEY (Role, PermissaoId),
    FOREIGN KEY (PermissaoId) REFERENCES Permissao(Id)
);
