------- CRIACAO DAS TABELAS

CREATE TABLE InsitutuicaoSaude (
    CNPJ VARCHAR(40) PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    cidade VARCHAR(40),
    estado VARCHAR(2),
    logradouro VARCHAR(100),
    CHECK (CNPJ LIKE '##.###.###/####-##'),
);

CREATE TABLE CentroColeta(
    CNPJ VARCHAR(18),
    codigo VARCHAR(10),
    cidade VARCHAR(40),
    estado VARCHAR(2),
    logradouro VARCHAR(100),
    ativo BOOLEAN,
    dataAbertura DATE,
    dataFechamento DATE,
    PRIMARY_KEY(CNPJ, codigo),
    FOREIGN KEY(CNPJ) REFERENCES InsitutuicaoSaude(CNPJ) ON DELETE CASCADE
);

CREATE TABLE EstoqueSangue(
    InsitutuicaoSaude VARCHAR(40) PRIMARY KEY,
    NumOMinus INTEGER,
    NumAMinus INTEGER,
    NumBMinus INTEGER,
    NumABMinus INTEGER,
    NumOPlus INTEGER,
    NumAPlus INTEGER,
    NumBPlus INTEGER,
    NumABPlus INTEGER,
    FOREIGN KEY (InsitutuicaoSaude) REFERENCES InsitutuicaoSaude(CNPJ) ON DELETE CASCADE
);

CREATE TABLE Pessoa(
    Id VARCHAR2(10) PRIMARY_KEY,
    nome VARCHAR2(40) NOT NULL,
    genero VARCHAR2(20),
    tiposanguineo CHAR(3),
    cidade VARCHAR2(40),
    estado CHAR(2),
    logradouro VARCHAR2(100),
    dataNascimento DATE NOT NULL,
    telefone CHAR(11),
    email VARCHAR2(30),
    cpf CHAR(11) UNIQUE,
    CONSTRAINT CHK_GENERO CHECK (GENERO IN ('MASCULINO', 'FEMININO', 'OUTRO')),
    CONSTRAINT CHK_CPF CHECK (CPF LIKE '###.###.###-##'),
    CONSTRAINT CHK_TELEFONE CHECK (TELEFONE LIKE '## #####-####'),
    CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE '%_@_%._%'),
    CONSTRAINT CHK_TIPOSANGUINEO CHECK (TIPOSANGUINEO IN ('O-', 'A-', 'B-', 'AB-', 'O+', 'A+', 'B+', 'AB+')),
);  

CREATE TABLE Biomedico(
    Id VARCHAR2(10) PRIMARY KEY,
    CRBM VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_BIOMEDICO FOREIGN KEY(Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE TABLE Enfermeiro(
    Id VARCHAR2(10) PRIMARY KEY,
    COREN VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_ENFERMEIRO FOREIGN KEY(Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE TABLE Medico(
    Id VARCHAR2(10) PRIMARY KEY,
    CRM VARCHAR2(10) UNIQUE,
    CONSTRAINT FK_MEDICO FOREIGN KEY(Id) REFERENCES Pessoa(Id) ON DELETE CASCADE
);

CREATE 



