from pydantic import BaseModel, Field, EmailStr
from typing import Optional
from datetime import date

class DoadorCreate(BaseModel):
    # Pessoa fields
    # id is generated by backend
    nome: str = Field(..., min_length=1, max_length=40)
    genero: str = Field(..., pattern="^(MASCULINO|FEMININO|OUTRO)$")
    tiposanguineo: Optional[str] = Field(None, pattern="^(O-|A-|B-|AB-|O\+|A\+|B\+|AB\+)$")
    cidade: Optional[str] = Field(None, max_length=40)
    estado: Optional[str] = Field(None, min_length=2, max_length=2)
    logradouro: Optional[str] = Field(None, max_length=100)
    dataNascimento: date
    telefone: Optional[str] = Field(None, min_length=11, max_length=15)
    email: Optional[EmailStr] = None
    cpf: Optional[str] = Field(None, min_length=11, max_length=14)
    
    # Doador specific fields
    peso: float = Field(..., gt=0)
    altura: float = Field(..., gt=0)

class EstoqueQuery(BaseModel):
    hemocentro_cnpj: Optional[str] = None
    min_volume: Optional[int] = 0

class PesquisaCreate(BaseModel):
    doador_id: str
    agente_id: str
    doou: bool
    primeira_doacao: bool
    doaria_novamente: bool
    feedback: Optional[str] = None

class ProcedimentoCreate(BaseModel):
    receptor_id: str
    medico_id: str
    hospital_cnpj: str

class TriagemCreate(BaseModel):
    doador_id: str
    enfermeiro_id: str
    centro_coleta_cnpj: str
    centro_coleta_codigo: str
    valido: bool

class BolsaSangueCreate(BaseModel):
    volume_doado: int
    tipo_sangue: str = Field(..., pattern="^(O-|A-|B-|AB-|O\+|A\+|B\+|AB\+)$")
    valido: bool
    triagem_id: str
    biomedico_id: str
    hemocentro_cnpj: str
    data_testagem: date

class SolicitacaoCreate(BaseModel):
    hospital_cnpj: str
    hemocentro_cnpj: str
    qnt_oplus: int = 0
    qnt_ominus: int = 0
    qnt_aplus: int = 0
    qnt_aminus: int = 0
    qnt_bplus: int = 0
    qnt_bminus: int = 0
    qnt_abplus: int = 0
    qnt_abminus: int = 0
    aceita_negada: bool = False
